In [41]:
import pandas as pd
import openpyxl
import requests

import pyEX as p

In [35]:
# Import iex cloud api token
from config import iex_api_token

In [86]:
# Read in all stocks (~10,000)
df = pd.read_excel('stock_list_all.xlsx')

# Chang the column labels to lowercase
df = df.rename(columns={col: col.lower() for col in df.columns})

# get length of df
len(df)

5449

In [87]:
# print head of df
df.head()

,symbol,company name,sector,industry
0,A,Agilent Technologies Inc,Health Care,Life Sciences Tools & Services
1,AA,Alcoa Corp,Materials,Metals & Mining
2,AACG,ATA Creativity Global(ADR),Consumer Discretionary,Diversified Consumer Services
3,AAL,American Airlines Group Inc,Industrials,Airlines
4,AAMC,Altisource Asset Management Corp,Real Estate,Real Estate Management & Development

In [88]:
""" DEV - Create a smaller stock list """

df = df.iloc[:11,:]

df

,symbol,company name,sector,industry
0,A,Agilent Technologies Inc,Health Care,Life Sciences Tools & Services
1,AA,Alcoa Corp,Materials,Metals & Mining
2,AACG,ATA Creativity Global(ADR),Consumer Discretionary,Diversified Consumer Services
3,AAL,American Airlines Group Inc,Industrials,Airlines
4,AAMC,Altisource Asset Management Corp,Real Estate,Real Estate Management & Development
5,AAME,Atlantic American Corporation,Financials,Insurance
6,AAN,"Aaron's, Inc.",Consumer Discretionary,Specialty Retail
7,AAOI,Applied Optoelectronics Inc,Information Technology,Communications Equipment
8,AAON,"AAON, Inc.",Industrials,Building Products
9,AAP,"Advance Auto Parts, Inc.",Consumer Discretionary,Specialty Retail
10,AAPL,Apple Inc.,Information Technology,"Technology Hardware, Storage & Peripherals"

In [89]:
# Get all the ticker symbols from the df
symbols_list = df['symbol'].values.tolist()

# verfiy that length matches and makes sense
len(symbols_list)

11

In [74]:
# Connect to IEX cloud api endpoint
c = p.Client(api_token=iex_api_token, version='stable')

In [ ]:
symbols_list

In [75]:
# Get dividend data
ticker = 'AAPL' # IMPORTANT - not all stocks issue dividends
timeframe = '6m'
df = c.dividendsDF(symbol=ticker)

df

,adrFee,amount,announceDate,countryCode,coupon,created,currency,declaredCurrencyCD,declaredDate,declaredGrossAmount,...,securityType,symbol,taxRate,toDate,toFactor,id,key,subkey,date,updated
0,0,0.23,2022-10-27,US,0,2022-10-28,USD,,2022-10-27,0,...,Equity Shares,AAPL,0,0000-00-00,0,ADVANCED_DIVIDENDS,AAPL,2733643,1667520000000,1667075238000

In [81]:
# Create a list of stocks that you know returns dividends
div_list = ['VFC', 'DVN', 'BBY', 'NLY', 'VZ', 'T', 'INTC', 'PM', 'WBA', 'MMM']

In [ ]:
# div_df = []
for i in div_list:
    staging_df = c.dividendsDF(symbol=i)

In [85]:
div_df = pd.DataFrame([c.dividendsDF(symbol=i) for i in div_list])

ValueError: Must pass 2-d input. shape=(11, 1, 48)

In [84]:
# Initialize df outside of loop
div_df = []

for i in div_list:
    timeframe = '6m'
    api_data = c.dividendsDF(symbol=i)
    div_df.extend(api_data)

div_df = pd.DataFrame(div_df)

div_df

                0
0          adrFee
1          amount
2    announceDate
3     countryCode
4          coupon
..            ...
523            id
524           key
525        subkey
526          date
527       updated

[528 rows x 1 columns]

In [79]:
div_df

['adrFee',
 'amount',
 'announceDate',
 'countryCode',
 'coupon',
 'created',
 'currency',
 'declaredCurrencyCD',
 'declaredDate',
 'declaredGrossAmount',
 'description',
 'exDate',
 'figi',
 'fiscalYearEndDate',
 'flag',
 'frequency',
 'fromFactor',
 'fxDate',
 'grossAmount',
 'installmentPayDate',
 'isApproximate',
 'isCapitalGains',
 'isDAP',
 'isNetInvestmentIncome',
 'lastUpdated',
 'marker',
 'netAmount',
 'notes',
 'optionalElectionDate',
 'parValue',
 'parValueCurrency',
 'paymentDate',
 'periodEndDate',
 'recordDate',
 'refid',
 'registrationDate',
 'secondExDate',
 'secondPaymentDate',
 'securityType',
 'symbol',
 'taxRate',
 'toDate',
 'toFactor',
 'id',
 'key',
 'subkey',
 'date',
 'updated',
 'adrFee',
 'amount',
 'announceDate',
 'countryCode',
 'coupon',
 'created',
 'currency',
 'declaredCurrencyCD',
 'declaredDate',
 'declaredGrossAmount',
 'description',
 'exDate',
 'figi',
 'fiscalYearEndDate',
 'flag',
 'frequency',
 'fromFactor',
 'fxDate',
 'grossAmount',
 'installmentPayDate',
 'isApproximate',
 'isCapitalGains',
 'isDAP',
 'isNetInvestmentIncome',
 'lastUpdated',
 'marker',
 'netAmount',
 'notes',
 'optionalElectionDate',
 'parValue',
 'parValueCurrency',
 'paymentDate',
 'periodEndDate',
 'recordDate',
 'refid',
 'registrationDate',
 'secondExDate',
 'secondPaymentDate',
 'securityType',
 'symbol',
 'taxRate',
 'toDate',
 'toFactor',
 'id',
 'key',
 'subkey',
 'date',
 'updated',
 'adrFee',
 'amount',
 'announceDate',
 'countryCode',
 'coupon',
 'created',
 'currency',
 'declaredCurrencyCD',
 'declaredDate',
 'declaredGrossAmount',
 'description',
 'exDate',
 'figi',
 'fiscalYearEndDate',
 'flag',
 'frequency',
 'fromFactor',
 'fxDate',
 'grossAmount',
 'installmentPayDate',
 'isApproximate',
 'isCapitalGains',
 'isDAP',
 'isNetInvestmentIncome',
 'lastUpdated',
 'marker',
 'netAmount',
 'notes',
 'optionalElectionDate',
 'parValue',
 'parValueCurrency',
 'paymentDate',
 'periodEndDate',
 'recordDate',
 'refid',
 'registrationDate',
 'secondExDate',
 'secondPaymentDate',
 'securityType',
 'symbol',
 'taxRate',
 'toDate',
 'toFactor',
 'id',
 'key',
 'subkey',
 'date',
 'updated',
 'adrFee',
 'amount',
 'announceDate',
 'countryCode',
 'coupon',
 'created',
 'currency',
 'declaredCurrencyCD',
 'declaredDate',
 'declaredGrossAmount',
 'description',
 'exDate',
 'figi',
 'fiscalYearEndDate',
 'flag',
 'frequency',
 'fromFactor',
 'fxDate',
 'grossAmount',
 'installmentPayDate',
 'isApproximate',
 'isCapitalGains',
 'isDAP',
 'isNetInvestmentIncome',
 'lastUpdated',
 'marker',
 'netAmount',
 'notes',
 'optionalElectionDate',
 'parValue',
 'parValueCurrency',
 'paymentDate',
 'periodEndDate',
 'recordDate',
 'refid',
 'registrationDate',
 'secondExDate',
 'secondPaymentDate',
 'securityType',
 'symbol',
 'taxRate',
 'toDate',
 'toFactor',
 'id',
 'key',
 'subkey',
 'date',
 'updated',
 'adrFee',
 'amount',
 'announceDate',
 'countryCode',
 'coupon',
 'created',
 'currency',
 'declaredCurrencyCD',
 'declaredDate',
 'declaredGrossAmount',
 'description',
 'exDate',
 'figi',
 'fiscalYearEndDate',
 'flag',
 'frequency',
 'fromFactor',
 'fxDate',
 'grossAmount',
 'installmentPayDate',
 'isApproximate',
 'isCapitalGains',
 'isDAP',
 'isNetInvestmentIncome',
 'lastUpdated',
 'marker',
 'netAmount',
 'notes',
 'optionalElectionDate',
 'parValue',
 'parValueCurrency',
 'paymentDate',
 'periodEndDate',
 'recordDate',
 'refid',
 'registrationDate',
 'secondExDate',
 'secondPaymentDate',
 'securityType',
 'symbol',
 'taxRate',
 'toDate',
 'toFactor',
 'id',
 'key',
 'subkey',
 'date',
 'updated',
 'adrFee',
 'amount',
 'announceDate',
 'countryCode',
 'coupon',
 'created',
 'currency',
 'declaredCurrencyCD',
 'declaredDate',
 'declaredGrossAmount',
 'description',
 'exDate',
 'figi',
 'fiscalYearEndDate',
 'flag',
 'frequency',
 'fromFactor',
 'fxDate',
 'grossAmount',
 'installmentPayDate',
 'isApproximate',
 'isCapitalGains',
 'isDAP',
 'isNetInvestmentIncome',
 'lastUpdated',
 'marker',
 'netAmount',
 'notes',
 'optionalElectionDate',
 'parValue',
 'parValueCurrency',
 'paymentDate',
 'periodEndDate',
 'recordDate',
 'refid',
 'registrationDate',
 'secondExDate',
 'secondPaymentDate',
 'securityType',
 'symbol',
 'taxRate',
 'toDate',
 'toFactor',
 'id',
 'key',
 'subkey',
 'date',
 'updated',
 'adrFee',
 'amount',
 'announceDate',
 'countryCode',
 'coupon',
 'created',
 'currency',
 'declaredCurrencyCD',
 'declaredDate',
 'declaredGrossAmount',
 'description',
 'exDate',
 'figi',
 'fiscalYearEndDate',
 'flag',
 'frequency',
 'fromFactor',
 'fxDate',
 'grossAmount',
 'installmentPayDate',
 'isApproximate',
 'isCapitalGains',
 'isDAP',
 'isNetInvestmentIncome',
 'lastUpdated',
 'marker',
 'netAmount',
 'notes',
 'optionalElectionDate',
 'parValue',
 'parValueCurrency',
 'paymentDate',
 'periodEndDate',
 'recordDate',
 'refid',
 'registrationDate',
 'secondExDate',
 'secondPaymentDate',
 'securityType',
 'symbol',
 'taxRate',
 'toDate',
 'toFactor',
 'id',
 'key',
 'subkey',
 'date',
 'updated',
 'adrFee',
 'amount',
 'announceDate',
 'countryCode',
 'coupon',
 'created',
 'currency',
 'declaredCurrencyCD',
 'declaredDate',
 'declaredGrossAmount',
 'description',
 'exDate',
 'figi',
 'fiscalYearEndDate',
 'flag',
 'frequency',
 'fromFactor',
 'fxDate',
 'grossAmount',
 'installmentPayDate',
 'isApproximate',
 'isCapitalGains',
 'isDAP',
 'isNetInvestmentIncome',
 'lastUpdated',
 'marker',
 'netAmount',
 'notes',
 'optionalElectionDate',
 'parValue',
 'parValueCurrency',
 'paymentDate',
 'periodEndDate',
 'recordDate',
 'refid',
 'registrationDate',
 'secondExDate',
 'secondPaymentDate',
 'securityType',
 'symbol',
 'taxRate',
 'toDate',
 'toFactor',
 'id',
 'key',
 'subkey',
 'date',
 'updated',
 'adrFee',
 'amount',
 'announceDate',
 'countryCode',
 'coupon',
 'created',
 'currency',
 'declaredCurrencyCD',
 'declaredDate',
 'declaredGrossAmount',
 'description',
 'exDate',
 'figi',
 'fiscalYearEndDate',
 'flag',
 'frequency',
 'fromFactor',
 'fxDate',
 'grossAmount',
 'installmentPayDate',
 'isApproximate',
 'isCapitalGains',
 'isDAP',
 'isNetInvestmentIncome',
 'lastUpdated',
 'marker',
 'netAmount',
 'notes',
 'optionalElectionDate',
 'parValue',
 'parValueCurrency',
 'paymentDate',
 'periodEndDate',
 'recordDate',
 'refid',
 'registrationDate',
 'secondExDate',
 'secondPaymentDate',
 'securityType',
 'symbol',
 'taxRate',
 'toDate',
 'toFactor',
 'id',
 'key',
 'subkey',
 'date',
 'updated']

| END OF PROGRAM |
| ----------- |
| Notes for future DEV, and reference code below |

In [ ]:
# # Get real time quote to makes sure api is working
# ticker = 'PLTR'
# rt = c.quote(symbol=ticker)

# rt

In [53]:
# Get dividend data
ticker = 'AAPL' # IMPORTANT - not all stocks issue dividends
timeframe = '6m'
df = c.dividendsDF(symbol=ticker)

df

,adrFee,amount,announceDate,countryCode,coupon,created,currency,declaredCurrencyCD,declaredDate,declaredGrossAmount,...,securityType,symbol,taxRate,toDate,toFactor,id,key,subkey,date,updated
0,0,0.23,2022-10-27,US,0,2022-10-28,USD,,2022-10-27,0,...,Equity Shares,AAPL,0,0000-00-00,0,ADVANCED_DIVIDENDS,AAPL,2733643,1667520000000,1667075238000

In [ ]:
""" DEV - Create a smaller stock list """

df_t = df.iloc['']

In [51]:
# Collect data with batch API requests

Empty DataFrame
Columns: []
Index: []

In [39]:
# Connect to IEX cloud
api_endpoint = "https://cloud.iexapis.com/stable"

# Set stock symbol to query
symbol = 'PLTR'

url = f"{api_endpoint}/stock/{symbol}/quote?token={iex_api_token}"

response = requests.get(url)

response.status_code # Look for 200

200

In [40]:
response.json()

{'avgTotalVolume': 26957219,
 'calculationPrice': 'tops',
 'change': -0.2,
 'changePercent': -0.02853,
 'close': 7.01,
 'closeSource': 'official',
 'closeTime': 1671138002246,
 'companyName': 'Palantir Technologies Inc - Class A',
 'currency': 'USD',
 'delayedPrice': 6.776,
 'delayedPriceTime': 1671208287300,
 'extendedChange': 0.21,
 'extendedChangePercent': 0.03084,
 'extendedPrice': 7.02,
 'extendedPriceTime': 1671200976894,
 'high': 7.08,
 'highSource': '15 minute delayed price',
 'highTime': 1671208287300,
 'iexAskPrice': 6.81,
 'iexAskSize': 469,
 'iexBidPrice': 6.8,
 'iexBidSize': 5900,
 'iexClose': 6.81,
 'iexCloseTime': 1671209162097,
 'iexLastUpdated': 1671209162097,
 'iexMarketPercent': 0.020915159228884563,
 'iexOpen': 7.01,
 'iexOpenTime': 1671201003080,
 'iexRealtimePrice': 6.81,
 'iexRealtimeSize': 200,
 'iexVolume': 295331,
 'lastTradeTime': 1671209162097,
 'latestPrice': 6.81,
 'latestSource': 'IEX real time price',
 'latestTime': '11:46:02 AM',
 'latestUpdate': 1671209162097,
 'latestVolume': 14120428,
 'low': 6.76,
 'lowSource': '15 minute delayed price',
 'lowTime': 1671208103090,
 'marketCap': 13479226690,
 'oddLotDelayedPrice': 6.775,
 'oddLotDelayedPriceTime': 1671208288284,
 'open': 7.01,
 'openTime': 1671201000000,
 'openSource': 'official',
 'peRatio': -24.83,
 'previousClose': 7.01,
 'previousVolume': 25417145,
 'primaryExchange': 'NEW YORK STOCK EXCHANGE INC.',
 'symbol': 'PLTR',
 'volume': 14120428,
 'week52High': 19.45,
 'week52Low': 6.44,
 'ytdChange': -0.643576677649643,
 'isUSMarketOpen': True}

In [33]:
# Hit the dividends endpoint
url = f"{api_endpoint}/time-series/advanced_dividends/{symbol}/?token={iex_api_token}"

response = requests.get(url)

response.status_code # Look for 200

200

In [34]:
# Look at JSON response
print(response.json())

[]