In [1]:
import pandas as pd
import openpyxl
import requests

import pyEX as p

In [2]:
# Import iex cloud api token
from config import iex_api_token

When you’re looking for ways to receive regular dividend payments, you generally have two options: stocks that pay dividends and funds that hold stocks that pay dividends.

In [4]:
# Connect to IEX cloud api endpoint
c = p.Client(api_token=iex_api_token, version='stable')

# Test api connection
ticker = 'AAPL' # IMPORTANT - not all stocks issue dividends
timeframe = '6m'
test_df = c.dividendsDF(symbol=ticker)

test_df

,adrFee,amount,announceDate,countryCode,coupon,created,currency,declaredCurrencyCD,declaredDate,declaredGrossAmount,...,securityType,symbol,taxRate,toDate,toFactor,id,key,subkey,date,updated
0,0,0.23,2022-10-27,US,0,2022-10-28,USD,,2022-10-27,0,...,Equity Shares,AAPL,0,0000-00-00,0,ADVANCED_DIVIDENDS,AAPL,2733643,1667520000000,1667075238000

In [5]:
# set the columns and covert from index object to list
col = test_df.columns
col_list = list(col)

# Create a pandas data frame with cols 
div_df = pd.DataFrame(columns=col_list)

div_df

Empty DataFrame
Columns: [adrFee, amount, announceDate, countryCode, coupon, created, currency, declaredCurrencyCD, declaredDate, declaredGrossAmount, description, exDate, figi, fiscalYearEndDate, flag, frequency, fromFactor, fxDate, grossAmount, installmentPayDate, isApproximate, isCapitalGains, isDAP, isNetInvestmentIncome, lastUpdated, marker, netAmount, notes, optionalElectionDate, parValue, parValueCurrency, paymentDate, periodEndDate, recordDate, refid, registrationDate, secondExDate, secondPaymentDate, securityType, symbol, taxRate, toDate, toFactor, id, key, subkey, date, updated]
Index: []

[0 rows x 48 columns]

In [7]:
# Create a list of stocks that you know issue stock dividends
div_list = ['VFC', 'DVN', 'BBY', 'NLY', 'VZ', 'T', 'INTC', 'PM', 'WBA', 'MMM']

for i in div_list:
    data_input_df = c.dividendsDF(symbol=i)
    div_df = div_df.append(data_input_df, ignore_index=True)

/var/folders/8w/4mj_4m4d0rs1q22bl9g77hhw0000gn/T/ipykernel_33189/3511670670.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  div_df = div_df.append(data_input_df, ignore_index=True)
/var/folders/8w/4mj_4m4d0rs1q22bl9g77hhw0000gn/T/ipykernel_33189/3511670670.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  div_df = div_df.append(data_input_df, ignore_index=True)
/var/folders/8w/4mj_4m4d0rs1q22bl9g77hhw0000gn/T/ipykernel_33189/3511670670.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  div_df = div_df.append(data_input_df, ignore_index=True)
/var/folders/8w/4mj_4m4d0rs1q22bl9g77hhw0000gn/T/ipykernel_33189/3511670670.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  div_df = div_df.append(data_input_df, ignore_index=True)
/var/folders/8w/4mj_4m4d0rs1q22bl9g77hhw0000gn/T/ipykernel_33189/3511670670.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  div_df = div_df.append(data_input_df, ignore_index=True)
/var/folders/8w/4mj_4m4d0rs1q22bl9g77hhw0000gn/T/ipykernel_33189/3511670670.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  div_df = div_df.append(data_input_df, ignore_index=True)
/var/folders/8w/4mj_4m4d0rs1q22bl9g77hhw0000gn/T/ipykernel_33189/3511670670.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  div_df = div_df.append(data_input_df, ignore_index=True)
/var/folders/8w/4mj_4m4d0rs1q22bl9g77hhw0000gn/T/ipykernel_33189/3511670670.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  div_df = div_df.append(data_input_df, ignore_index=True)
/var/folders/8w/4mj_4m4d0rs1q22bl9g77hhw0000gn/T/ipykernel_33189/3511670670.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  div_df = div_df.append(data_input_df, ignore_index=True)
/var/folders/8w/4mj_4m4d0rs1q22bl9g77hhw0000gn/T/ipykernel_33189/3511670670.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  div_df = div_df.append(data_input_df, ignore_index=True)

In [41]:
# Look at the staging df
div_df

,adrFee,amount,announceDate,countryCode,coupon,created,currency,declaredCurrencyCD,declaredDate,declaredGrossAmount,...,securityType,symbol,taxRate,toDate,toFactor,id,key,subkey,date,updated
0,0,0.5100,2022-10-26,US,0,2022-10-27,USD,,2022-10-26,0,...,Equity Shares,VFC,0,0000-00-00,0,ADVANCED_DIVIDENDS,VFC,2733060,1670544000000,1670617336000
1,0,1.1700,2022-11-01,US,0,2022-12-10,USD,,2022-11-01,0,...,Equity Shares,DVN,0,0000-00-00,0,ADVANCED_DIVIDENDS,DVN,2777170,1670544000000,1670962814000
2,0,0.8800,2022-11-22,US,0,2022-11-22,USD,,2022-11-22,0,...,Equity Shares,BBY,0,0000-00-00,0,ADVANCED_DIVIDENDS,BBY,2758555,1670803200000,1670703611000
3,0,0.8800,2022-12-08,US,0,2022-12-09,USD,,2022-12-08,0,...,Equity Shares,NLY,0,0000-00-00,0,ADVANCED_DIVIDENDS,NLY,2775844,1672272000000,1670703623000
4,0,0.6525,2022-12-01,US,0,2022-12-02,USD,,2022-12-01,0,...,Equity Shares,VZ,0,0000-00-00,0,ADVANCED_DIVIDENDS,VZ,2764527,1673222400000,1670098936000
5,0,0.2775,2022-12-15,US,0,2022-12-16,USD,,2022-12-15,0,...,Equity Shares,T,0,0000-00-00,0,ADVANCED_DIVIDENDS,T,2793339,1673222400000,1671207632000
6,0,0.3650,2022-09-16,US,0,2022-09-16,USD,,2022-09-16,0,...,Equity Shares,INTC,0,0000-00-00,0,ADVANCED_DIVIDENDS,INTC,2700803,1667520000000,1663705250000
7,0,1.2700,2022-12-08,US,0,2022-12-09,USD,,2022-12-08,0,...,Equity Shares,PM,0,0000-00-00,0,ADVANCED_DIVIDENDS,PM,2775841,1671580800000,1670703624000
8,0,0.4800,2022-10-27,US,0,2022-10-28,USD,,2022-10-27,0,...,Equity Shares,WBA,0,0000-00-00,0,ADVANCED_DIVIDENDS,WBA,2733831,1668384000000,1667075213000
9,0,1.4900,2022-11-08,US,0,2022-11-09,USD,,2022-11-08,0,...,Equity Shares,MMM,0,0000-00-00,0,ADVANCED_DIVIDENDS,MMM,2744458,1668643200000,1668112048000

In [42]:
# Drop columns 
div_df = div_df.drop(columns = ['adrFee', 'coupon', 'declaredCurrencyCD', 'declaredGrossAmount', 'id', 'key', 'figi', 
'fiscalYearEndDate', 'secondExDate', 'secondPaymentDate', 'securityType', 'toDate', 'toFactor', 'date', 'updated', 'parValue',
'parValueCurrency', 'periodEndDate', 'recordDate', 'refid', 'registrationDate', 'taxRate', 'subkey',
'isApproximate', 'isCapitalGains', 'isDAP', 'isNetInvestmentIncome', 'marker', 'netAmount', 'notes', 'optionalElectionDate',
'description', 'flag', 'fromFactor', 'fxDate', 'installmentPayDate', 'announceDate', 'created', 'grossAmount',
'declaredDate', 'lastUpdated', 'countryCode'])

div_df

   amount currency      exDate  frequency paymentDate symbol
0  0.5100      USD  2022-12-09  quarterly  2022-12-20    VFC
1  1.1700      USD  2022-12-09  irregular  2022-12-30    DVN
2  0.8800      USD  2022-12-12  quarterly  2023-01-03    BBY
3  0.8800      USD  2022-12-29  quarterly  2023-01-31    NLY
4  0.6525      USD  2023-01-09  quarterly  2023-02-01     VZ
5  0.2775      USD  2023-01-09  quarterly  2023-02-01      T
6  0.3650      USD  2022-11-04  quarterly  2022-12-01   INTC
7  1.2700      USD  2022-12-21  quarterly  2023-01-11     PM
8  0.4800      USD  2022-11-14  quarterly  2022-12-12    WBA
9  1.4900      USD  2022-11-17  quarterly  2022-12-12    MMM

In [43]:
# set column order
column_order = ['symbol', 'exDate', 'paymentDate', 'frequency', 'currency', 'amount']
div_df = div_df[column_order]

div_df

  symbol      exDate paymentDate  frequency currency  amount
0    VFC  2022-12-09  2022-12-20  quarterly      USD  0.5100
1    DVN  2022-12-09  2022-12-30  irregular      USD  1.1700
2    BBY  2022-12-12  2023-01-03  quarterly      USD  0.8800
3    NLY  2022-12-29  2023-01-31  quarterly      USD  0.8800
4     VZ  2023-01-09  2023-02-01  quarterly      USD  0.6525
5      T  2023-01-09  2023-02-01  quarterly      USD  0.2775
6   INTC  2022-11-04  2022-12-01  quarterly      USD  0.3650
7     PM  2022-12-21  2023-01-11  quarterly      USD  1.2700
8    WBA  2022-11-14  2022-12-12  quarterly      USD  0.4800
9    MMM  2022-11-17  2022-12-12  quarterly      USD  1.4900

| END OF PROGRAM |
| ----------- |
| Notes for future DEV, and reference code below |

In [ ]:
# Determine which stocks offer dividends -> using the financials iex cloud endpoint

In [ ]:
# Filter out stocks that don't offer dividends

In [ ]:
# Sort data frame so that highest return dividend stocks are listed first

In [ ]:
# Reset index and drop extra useless old index column